/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated user's portfolios
         * @description Returns a light list view — one row per portfolio, suitable for a dashboard/landing.
         */
        get: operations["listPortfolios"];
        put?: never;
        /** Create a new portfolio */
        post: operations["createPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single portfolio with full summary data
         * @description Returns everything the Portfolio Summary screen needs **except** the
         *     time-series measurements (those are at `/portfolios/{slug}/performance`
         *     because they can be large and are cached separately).
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        /** Delete a portfolio and its snapshot */
        delete: operations["deletePortfolio"];
        options?: never;
        head?: never;
        /** Update portfolio name, schedule, or parameters */
        patch: operations["updatePortfolio"];
        trace?: never;
    };
    "/portfolios/{slug}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Equity-curve time series
         * @description Daily measurements. Optionally filter by date range; when omitted,
         *     returns the full series from inception to today.
         */
        get: operations["getPortfolioPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest transactions (buys, sells, dividends, etc.) */
        get: operations["getPortfolioTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run history for a portfolio */
        get: operations["listPortfolioRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a one-shot backtest for the portfolio */
        post: operations["triggerPortfolioRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade portfolio to the latest installed strategy version
         * @description Re-pins the portfolio to the registry's currently installed strategy version
         *     and dispatches a fresh backtest run. If the supplied (or stored) parameters
         *     are compatible with the new describe, no body is required.
         *
         *     If parameters cannot be auto-merged (any removed, retyped, or added-without-default),
         *     the response is 409 with a structured diff and the new describe; the client must
         *     resubmit the call with an explicit `parameters` map validated against the new describe.
         */
        post: operations["upgradePortfolioStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail for a single run */
        get: operations["getPortfolioRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/runs/{runId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream backtest progress as Server-Sent Events
         * @description Opens an SSE stream for the given run. Each event is either a
         *     `progress` event (mid-run step update) or a terminal `done`/`error`
         *     event, after which the server closes the connection.
         */
        get: operations["streamRunProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-line KPIs from the latest successful backtest */
        get: operations["getPortfolioSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/drawdowns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drawdown list ordered by depth (deepest first) */
        get: operations["getPortfolioDrawdowns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk and style statistics */
        get: operations["getPortfolioStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All pvbt metrics grouped by category, filterable by window and name */
        get: operations["getPortfolioMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/trailing-returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trailing-returns rows (portfolio, benchmark, portfolio-tax, benchmark-tax) */
        get: operations["getPortfolioTrailingReturns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest holdings */
        get: operations["getPortfolioHoldings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/holdings/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical holdings as of a given date */
        get: operations["getPortfolioHoldingsAsOf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/holdings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-batch holdings history across the backtest */
        get: operations["getPortfolioHoldingsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/holdings-impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-ticker contribution to portfolio return across canonical periods. */
        get: operations["getPortfolioHoldingsImpact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts for a portfolio */
        get: operations["listPortfolioAlerts"];
        put?: never;
        /** Create a new alert for a portfolio */
        post: operations["createPortfolioAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{slug}/alerts/{alertId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an alert */
        delete: operations["deletePortfolioAlert"];
        options?: never;
        head?: never;
        /** Update an existing alert */
        patch: operations["updatePortfolioAlert"];
        trace?: never;
    };
    "/portfolios/{slug}/email-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a portfolio summary email on demand
         * @description Sends the current portfolio summary email to a single recipient. Intended for testing the email pipeline without waiting for a scheduled run.
         */
        post: operations["sendPortfolioEmailSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategies in the registry */
        get: operations["listStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clone, build, and describe a strategy repository */
        get: operations["describeStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{shortCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy detail */
        get: operations["getStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details. */
        Problem: {
            /**
             * Format: uri
             * @description URI identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference that identifies the specific occurrence.
             */
            instance?: string;
        };
        /**
         * @description How the value should be rendered. Percent values are decimal (0.1147 = 11.47%).
         * @enum {string}
         */
        MetricFormat: "number" | "percent";
        /**
         * @description Which line in the trailing returns table.
         * @enum {string}
         */
        ReturnRowKind: "portfolio" | "benchmark" | "portfolio-tax" | "benchmark-tax";
        /** @description Portfolio configuration. Derived backtest output lives on separate endpoints. */
        Portfolio: {
            /** @example adm-aggressive-gm59 */
            slug: string;
            /** @example ADM aggressive */
            name: string;
            status: components["schemas"]["PortfolioStatus"];
            strategyCode: string;
            /**
             * Format: uri
             * @description Clone URL for unofficial strategies; empty string for official ones.
             */
            strategyCloneUrl?: string;
            /** @description Pinned strategy version (null for unofficial portfolios). */
            strategyVer?: string | null;
            parameters: {
                [key: string]: unknown;
            };
            /** @description Name of the matched strategy preset, or null when parameters did not match a preset. */
            presetName?: string | null;
            /** @example SPY */
            benchmark: string;
            /**
             * Format: date
             * @description Backtest start date (YYYY-MM-DD). Absent or null means strategy default.
             */
            startDate?: string | null;
            /**
             * Format: date
             * @description Backtest end date (YYYY-MM-DD). Absent or null means today.
             */
            endDate?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Number of recent backtest runs to retain. Defaults to 2; minimum 1.
             * @default 2
             */
            runRetention: number;
            /** Format: date-time */
            lastRunAt?: string | null;
            lastError?: string | null;
            /**
             * Format: double
             * @description Latest portfolio equity from the most recent successful run. Null until a run has succeeded.
             */
            currentValue?: number | null;
            /**
             * Format: double
             * @description Year-to-date return as a decimal fraction. Null until a run has succeeded.
             */
            ytdReturn?: number | null;
            /**
             * Format: double
             * @description Worst peak-to-trough drawdown over the inception window, as a negative decimal fraction. Null until a run has succeeded.
             */
            maxDrawDown?: number | null;
            /**
             * Format: double
             * @description Annualized Sharpe ratio over the inception window. Null until a run has succeeded.
             */
            sharpe?: number | null;
            /**
             * Format: double
             * @description Compound annual growth rate from inception to the latest equity row, as a decimal fraction. Null until a run has succeeded.
             */
            cagrSinceInception?: number | null;
            /**
             * Format: date
             * @description First date of the equity series; pinned on the first successful run.
             */
            inceptionDate?: string | null;
        };
        PortfolioCreated: components["schemas"]["Portfolio"] & {
            /**
             * Format: uuid
             * @description ID of the backtest run automatically queued on creation. Present only when a dispatcher is configured; use with the SSE progress endpoint.
             */
            runId?: string;
        };
        /** @description Top-line numbers for the KPI strip. */
        PortfolioSummary: {
            /** Format: double */
            currentValue: number;
            /** Format: double */
            ytdReturn: number;
            /** Format: double */
            benchmarkYtdReturn: number;
            /** Format: double */
            oneYearReturn: number;
            /** Format: double */
            cagrSinceInception: number;
            /** Format: double */
            maxDrawDown: number;
            /** Format: double */
            sharpe: number;
            /** Format: double */
            sortino: number;
            /** Format: double */
            beta: number;
            /** Format: double */
            alpha: number;
            /** Format: double */
            stdDev: number;
            /** Format: double */
            ulcerIndex?: number;
            /** Format: double */
            taxCostRatio: number;
        };
        Drawdown: {
            /**
             * Format: date
             * @description Peak date when the drawdown began.
             */
            start: string;
            /**
             * Format: date
             * @description Date of the deepest point.
             */
            trough: string;
            /**
             * Format: date
             * @description Date equity returned to the prior peak. Null if unrecovered.
             */
            recovery?: string | null;
            /**
             * Format: double
             * @description Decimal percent, negative (e.g. -0.1670 = −16.70%).
             */
            depth: number;
            /** @description Trading days from start to recovery (or end of series if unrecovered). */
            days?: number;
        };
        PortfolioStatistic: {
            label: string;
            /** Format: double */
            value: number;
            format: components["schemas"]["MetricFormat"];
        };
        /** @description Map of pvbt metric name to array of values, one per requested window. */
        MetricGroup: {
            [key: string]: (number | null)[];
        };
        /** @description All pvbt metrics grouped by category, column-oriented against a shared windows list. */
        PortfolioMetrics: {
            /** @description Ordered list of requested windows. Each metric value array is aligned to this list. */
            windows: string[];
            summary?: components["schemas"]["MetricGroup"];
            risk?: components["schemas"]["MetricGroup"];
            trade?: components["schemas"]["MetricGroup"];
            withdrawal?: components["schemas"]["MetricGroup"];
            tax?: components["schemas"]["MetricGroup"];
            advanced?: components["schemas"]["MetricGroup"];
        };
        /**
         * @description Trailing returns for a portfolio or its benchmark. Sub-annual cells
         *     (ytd, oneYear) are cumulative period returns. Multi-year cells
         *     (threeYear, fiveYear, tenYear, sinceInception) are annualized (CAGR).
         *     Any cell is null when the snapshot does not span the requested window.
         */
        TrailingReturnRow: {
            title: string;
            kind: components["schemas"]["ReturnRowKind"];
            /** Format: double */
            ytd?: number | null;
            /** Format: double */
            oneYear?: number | null;
            /** Format: double */
            threeYear?: number | null;
            /** Format: double */
            fiveYear?: number | null;
            /** Format: double */
            tenYear?: number | null;
            /** Format: double */
            sinceInception?: number | null;
        };
        Holding: {
            /** @example VTI */
            ticker: string;
            figi?: string | null;
            /** Format: double */
            quantity: number;
            /** Format: double */
            avgCost: number;
            /** Format: double */
            marketValue: number;
            /**
             * Format: double
             * @description Decimal percent since previous close.
             */
            dayChange?: number | null;
        };
        HoldingsResponse: {
            /** Format: date */
            date: string;
            items: components["schemas"]["Holding"][];
            /** Format: double */
            totalMarketValue: number;
        };
        /**
         * @description Position reconstructed by replaying transactions. lastTradeValue is
         *     quantity × last trade price seen in the transaction log, not a
         *     mark-to-market value from a pricing feed.
         */
        HistoricalHolding: {
            /** @example VTI */
            ticker: string;
            figi?: string | null;
            /** Format: double */
            quantity: number;
            /** Format: double */
            avgCost: number;
            /** Format: double */
            lastTradeValue: number;
        };
        HoldingsAsOfResponse: {
            /** Format: date */
            date: string;
            items: components["schemas"]["HistoricalHolding"][];
            /** Format: double */
            totalLastTradeValue: number;
        };
        PortfolioPerformance: {
            portfolioSlug: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @enum {string} */
            resolution?: "daily" | "weekly" | "monthly";
            points: components["schemas"]["PerformancePoint"][];
        };
        PerformancePoint: {
            /** Format: date */
            date: string;
            /** Format: double */
            portfolioValue: number;
            /**
             * Format: double
             * @description Normalized to start at the portfolio's opening value.
             */
            benchmarkValue: number;
            /**
             * Format: double
             * @description Annualized risk-free rate at this date (e.g. 3-month T-Bill). Optional.
             */
            riskFreeRate?: number;
        };
        Transaction: {
            /**
             * Format: int64
             * @description Batch (rebalance event) this transaction belongs to.
             */
            batchId: number;
            /** Format: date */
            date: string;
            /** @enum {string} */
            type: "buy" | "sell" | "dividend" | "fee" | "deposit" | "withdrawal" | "split" | "interest" | "journal";
            ticker?: string | null;
            figi?: string | null;
            /** Format: double */
            quantity?: number;
            /** Format: double */
            price?: number;
            /** Format: double */
            amount?: number;
            qualified?: boolean | null;
            justification?: string | null;
        };
        TransactionsResponse: {
            items: components["schemas"]["Transaction"][];
        };
        HoldingsHistoryEntry: {
            /** Format: int64 */
            batchId: number;
            /** Format: date-time */
            timestamp: string;
            items: components["schemas"]["HistoricalHolding"][];
            /**
             * Format: double
             * @description Authoritative mark-to-market portfolio total on the batch's date,
             *     read from perf_data. Null when no perf_data row exists for that
             *     date (e.g. batch timestamp falls outside the equity curve).
             */
            portfolioValue?: number | null;
            /** @description Optional strategy-written key/value labels for this batch. */
            annotations?: {
                [key: string]: string;
            };
        };
        HoldingsHistoryResponse: {
            items: components["schemas"]["HoldingsHistoryEntry"][];
        };
        HoldingsImpactResponse: {
            portfolioSlug: string;
            /** Format: date */
            asOf: string;
            /**
             * @description ISO 4217 currency code of the portfolio's reporting currency.
             * @example USD
             */
            currency: string;
            periods: components["schemas"]["HoldingsImpactPeriod"][];
        };
        HoldingsImpactPeriod: {
            /** @enum {string} */
            period: "inception" | "5y" | "3y" | "1y" | "ytd";
            label: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: double */
            years: number;
            /** Format: double */
            cumulativeReturn: number;
            /** Format: double */
            annualizedReturn: number;
            items: components["schemas"]["HoldingsImpactItem"][];
            rest: components["schemas"]["HoldingsImpactRest"];
        };
        HoldingsImpactItem: {
            ticker: string;
            /** @description Composite FIGI. Empty string for synthetic tickers like $CASH. */
            figi?: string | null;
            /** Format: double */
            contribution: number;
            /** Format: double */
            avgWeight: number;
            /** Format: int64 */
            holdingDays: number;
        };
        HoldingsImpactRest: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            contribution: number;
        };
        /**
         * @description Current lifecycle status of the portfolio's backtest.
         * @enum {string}
         */
        PortfolioStatus: "pending" | "running" | "ready" | "failed";
        /** @enum {string} */
        StrategyInstallState: "pending" | "installing" | "ready" | "failed";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "success" | "failed";
        /**
         * @description Exactly one of `strategyCode` or `strategyCloneUrl` must be provided;
         *     supplying both or neither returns 422. Enforced by the handler, not
         *     by the JSON schema (oneOf omitted to keep the generated Go type flat).
         */
        PortfolioCreateRequest: {
            /** @description User-visible display name. */
            name: string;
            /** @description Strategy short code (from `describe` output). */
            strategyCode?: string;
            /**
             * Format: uri
             * @description HTTPS GitHub clone URL. Mutually exclusive with strategyCode.
             */
            strategyCloneUrl?: string;
            /** @description Specific version to pin; omit for latest installed. */
            strategyVer?: string;
            /** @description Values validated against the strategy's declared parameters. */
            parameters: {
                [key: string]: unknown;
            };
            /** @default SPY */
            benchmark: string;
            /**
             * Format: date
             * @description Backtest start date (YYYY-MM-DD). Omit to use the strategy default.
             */
            startDate?: string;
            /**
             * Format: date
             * @description Backtest end date (YYYY-MM-DD). Omit to use today.
             */
            endDate?: string;
            /**
             * @description Number of recent backtest runs to retain. Defaults to 2; minimum 1.
             * @default 2
             */
            runRetention: number;
        };
        /**
         * @description PATCH body. Only `name`, `startDate`, `endDate`, and `runRetention` are mutable.
         *     Any other field is rejected with 422. All fields are optional; omit
         *     any field you do not want to change.
         */
        PortfolioUpdateRequest: {
            name?: string;
            /**
             * Format: date
             * @description Backtest start date (YYYY-MM-DD).
             */
            startDate?: string;
            /**
             * Format: date
             * @description Backtest end date (YYYY-MM-DD).
             */
            endDate?: string;
            /**
             * @description Number of recent backtest runs to retain. Defaults to 2; minimum 1.
             * @default 2
             */
            runRetention: number;
        };
        /**
         * @description Returned with a `202 Accepted` status from the snapshot-reading
         *     endpoints when the portfolio's run database is missing and a
         *     recompute has been queued. Clients should poll `pollUrl` until the
         *     underlying run reaches a terminal status, then retry the original
         *     request.
         */
        RecalculatingResponse: {
            /**
             * @description Always the literal `recalculating`.
             * @enum {string}
             */
            status: "recalculating";
            /**
             * Format: uuid
             * @description ID of the queued or in-flight backtest run.
             */
            runId: string;
            portfolioSlug: string;
            /** @description Lifecycle status of the run at the time of the response. */
            runStatus: components["schemas"]["RunStatus"];
            /** @description URL to GET for run status (`/portfolios/{slug}/runs/{runId}`). */
            pollUrl: string;
            /** @description Human-readable explanation suitable for surfacing in a UI. */
            message?: string;
        };
        BacktestRun: {
            /** Format: uuid */
            id: string;
            portfolioSlug: string;
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            durationMs?: number | null;
            error?: string | null;
        };
        /** @description SSE data payload for a `progress` event during an active backtest run. */
        RunProgressEvent: {
            /** Format: int64 */
            step: number;
            /** Format: int64 */
            totalSteps: number;
            /** Format: date */
            currentDate?: string;
            /** Format: date */
            targetDate?: string;
            /** Format: double */
            pct: number;
            /** Format: int64 */
            elapsedMs?: number;
            /** Format: int64 */
            etaMs?: number;
            /** Format: int64 */
            measurements?: number;
        };
        /** @description SSE data payload for the terminal `done` or `error` event. */
        RunTerminalEvent: {
            status: components["schemas"]["RunStatus"];
            /** @description Error message; present only when status is `failed`. */
            error?: string;
        };
        Strategy: {
            shortCode: string;
            repoOwner: string;
            repoName: string;
            /** Format: uri */
            cloneUrl?: string;
            isOfficial: boolean;
            /** @description Auth0 sub of the registering user; NULL for official strategies. */
            ownerSub?: string | null;
            description?: string | null;
            categories?: string[];
            stars?: number | null;
            installState: components["schemas"]["StrategyInstallState"];
            installedVer?: string | null;
            lastAttemptedVer?: string | null;
            installError?: string | null;
            /** Format: date-time */
            installedAt?: string | null;
            describe?: components["schemas"]["StrategyDescribe"] | null;
            /** Format: double */
            cagr?: number | null;
            /** Format: double */
            maxDrawDown?: number | null;
            /** Format: double */
            sharpe?: number | null;
            /** Format: double */
            sortino?: number | null;
            /** Format: double */
            ulcerIndex?: number | null;
            /** Format: double */
            beta?: number | null;
            /** Format: double */
            alpha?: number | null;
            /** Format: double */
            stdDev?: number | null;
            /** Format: double */
            taxCostRatio?: number | null;
            /** Format: double */
            oneYearReturn?: number | null;
            /** Format: double */
            ytdReturn?: number | null;
            /** Format: double */
            benchmarkYtdReturn?: number | null;
        };
        StrategyDescribe: {
            shortCode: string;
            name: string;
            description?: string | null;
            parameters: components["schemas"]["StrategyParameter"][];
            presets?: components["schemas"]["StrategyPreset"][];
            schedule: string;
            benchmark: string;
        };
        StrategyParameter: {
            name: string;
            type: string;
            /** @description Default value — may be any JSON-serializable type. */
            default?: unknown;
            description?: string | null;
        };
        StrategyPreset: {
            name: string;
            parameters: {
                [key: string]: unknown;
            };
        };
        /**
         * @description How often the alert fires. `scheduled_run` fires on every completed backtest run; the others fire on calendar cadence.
         * @enum {string}
         */
        AlertFrequency: "scheduled_run" | "daily" | "weekly" | "monthly";
        Alert: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            portfolioId: string;
            frequency: components["schemas"]["AlertFrequency"];
            /** @description Email addresses that receive the alert. */
            recipients: string[];
            /** Format: date-time */
            lastSentAt?: string | null;
        };
        AlertCreateRequest: {
            frequency: components["schemas"]["AlertFrequency"];
            /** @description At least one recipient required. */
            recipients: string[];
        };
        /** @description All fields optional; omit any field you do not want to change. */
        AlertUpdateRequest: {
            frequency?: components["schemas"]["AlertFrequency"];
            recipients?: string[];
        };
        EmailSummaryRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            recipient: string;
        };
    };
    responses: {
        /** @description The request was rejected before handler logic ran. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested resource does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The target resource already exists or conflicts with an existing row. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request body was well-formed but failed validation. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The snapshot for this portfolio is missing or has been evicted, and a
         *     backtest run has been queued (or is already in flight) to rebuild it.
         *     The body carries the run id and a poll URL the client can GET to
         *     observe progress to completion.
         */
        Recalculating: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RecalculatingResponse"];
            };
        };
    };
    parameters: {
        /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
        PortfolioSlug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPortfolios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of portfolios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    createPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreateRequest"];
            };
        };
        responses: {
            /** @description Portfolio created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    deletePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    updatePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioUpdateRequest"];
            };
        };
        responses: {
            /** @description Portfolio updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioPerformance: {
        parameters: {
            query?: {
                /** @description ISO date (YYYY-MM-DD). Inclusive. */
                from?: string;
                /** @description ISO date (YYYY-MM-DD). Inclusive. */
                to?: string;
                /** @description Downsample target. `daily` (default) or `weekly`/`monthly` for coarser series. */
                resolution?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Equity-curve time series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioPerformance"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioTransactions: {
        parameters: {
            query?: {
                /** @description Inclusive start date (YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive end date (YYYY-MM-DD). */
                to?: string;
                /** @description Comma-separated list of transaction types to include. */
                type?: string;
            };
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    listPortfolioRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRun"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    triggerPortfolioRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    upgradePortfolioStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Explicit parameter values, validated against the new describe.
                     *     Required only if a prior call returned 409 parameters_incompatible.
                     */
                    parameters?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Upgraded, or already at latest. The body's `status` field disambiguates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "upgraded" | "already_at_latest";
                        from_version?: string;
                        to_version?: string;
                        /** @description Set on already_at_latest only. */
                        version?: string;
                        /**
                         * Format: uuid
                         * @description Set on `upgraded` when a dispatcher is configured.
                         */
                        run_id?: string;
                    };
                };
            };
            /** @description Resubmit body invalid (missing required parameter or unknown key). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Either a run is already in progress (`error: run_in_progress`),
             *     or parameters cannot be auto-merged and a resubmit is required
             *     (`error: parameters_incompatible`, with `incompatibilities` and `new_describe`).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error?: "run_in_progress" | "parameters_incompatible";
                        from_version?: string;
                        to_version?: string;
                        incompatibilities?: {
                            removed?: string[];
                            added_without_default?: string[];
                            retyped?: {
                                name?: string;
                                from?: string;
                                to?: string;
                            }[];
                        };
                        current_parameters?: {
                            [key: string]: unknown;
                        };
                        new_describe?: Record<string, never>;
                    };
                };
            };
            /** @description Strategy is not installable (no registry row, missing installed_ver, or install_error set). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error?: "strategy_not_installable";
                    };
                };
            };
            500: components["responses"]["ServerError"];
            /** @description Backtest queue is full; portfolio was upgraded but no run was queued. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPortfolioRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
                /** @description Run UUID. */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    streamRunProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
                /** @description Run UUID. */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of progress and terminal events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioDrawdowns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drawdowns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drawdown"][];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk/style statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioStatistic"][];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioMetrics: {
        parameters: {
            query?: {
                /** @description One or more windows to include. Repeatable. Default is since_inception. */
                window?: ("since_inception" | "5yr" | "3yr" | "1yr" | "ytd" | "mtd" | "wtd")[];
                /** @description One or more pvbt PascalCase metric names to include. Repeatable. Default is all metrics. */
                metric?: ("TWRR" | "MWRR" | "Sharpe" | "Sortino" | "Calmar" | "KellerRatio" | "MaxDrawdown" | "StdDev" | "Beta" | "Alpha" | "TrackingError" | "DownsideDeviation" | "InformationRatio" | "Treynor" | "UlcerIndex" | "ExcessKurtosis" | "Skewness" | "RSquared" | "ValueAtRisk" | "UpsideCaptureRatio" | "DownsideCaptureRatio" | "WinRate" | "AverageWin" | "AverageLoss" | "ProfitFactor" | "AverageHoldingPeriod" | "Turnover" | "NPositivePeriods" | "TradeGainLossRatio" | "AverageMFE" | "AverageMAE" | "MedianMFE" | "MedianMAE" | "EdgeRatio" | "TradeCaptureRatio" | "LongWinRate" | "ShortWinRate" | "LongProfitFactor" | "ShortProfitFactor" | "SafeWithdrawalRate" | "PerpetualWithdrawalRate" | "DynamicWithdrawalRate" | "LTCG" | "STCG" | "UnrealizedLTCG" | "UnrealizedSTCG" | "QualifiedDividends" | "NonQualifiedIncome" | "TaxCostRatio" | "TaxDrag" | "CAGR" | "ActiveReturn" | "SmartSharpe" | "SmartSortino" | "ProbabilisticSharpe" | "KRatio" | "KellyCriterion" | "OmegaRatio" | "GainToPainRatio" | "CVaR" | "TailRatio" | "RecoveryFactor" | "Exposure" | "ConsecutiveWins" | "ConsecutiveLosses" | "AvgDrawdown" | "AvgDrawdownDays" | "GainLossRatio" | "AvgUlcerIndex" | "P90UlcerIndex" | "MedianUlcerIndex")[];
            };
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics grouped by category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioMetrics"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioTrailingReturns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trailing returns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrailingReturnRow"][];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsResponse"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioHoldingsAsOf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings as of the given date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsAsOfResponse"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioHoldingsHistory: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound on batch timestamp (YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive upper bound on batch timestamp (YYYY-MM-DD). */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-batch holdings history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsHistoryResponse"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getPortfolioHoldingsImpact: {
        parameters: {
            query?: {
                /** @description Maximum number of named holdings per period (remaining folded into `rest`). Values outside [1, 50] are clamped silently. */
                top?: number;
            };
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings impact across canonical periods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsImpactResponse"];
                };
            };
            202: components["responses"]["Recalculating"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    listPortfolioAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    createPortfolioAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreateRequest"];
            };
        };
        responses: {
            /** @description Alert created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    deletePortfolioAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    updatePortfolioAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
                alertId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdateRequest"];
            };
        };
        responses: {
            /** @description Alert updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    sendPortfolioEmailSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Portfolio slug, e.g. `adm-aggressive-gm59`. */
                slug: components["parameters"]["PortfolioSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSummaryRequest"];
            };
        };
        responses: {
            /** @description Email accepted for delivery */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            /** @description Email sending is not configured on this server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of strategies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    describeStrategy: {
        parameters: {
            query: {
                /** @description HTTPS GitHub clone URL. */
                cloneUrl: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Describe output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDescribe"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    getStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
}
